### ISSUE TITLE
琴葉茜が琴葉葵になる

### ISSUE THREAD

**Issue by abokado0107** [Nkyoku/voiceroid_daemon#5]
voiceroid_daemonで茜のボイスライブラリ (akane_west_emo_44)を選択しても葵 (aoi_emo_44)の声や抑揚とまったく同じになってしまいます。
実行環境はwindows 10 Pro 21H2です。

試したこと
- 言語をstandardに変更
- 言語をstandard_kansaiに変更
- ライブラリをコピペして別名で保存

何か心当たりはございますか？
お返事お待ちしております。

**Comment by Nkyoku** [comment]
1つのボイスライブラリ内に2つの話者が存在する例かもしれないので以下を試していただけますか。

Python3 (バージョン3.4以上)をインストールし
コマンドプロンプトやPowerShellにて以下を実行してPython版のラッパーライブラリ`pyvcroid2`をインストールする。
```
pip install git+https://github.com/Nkyoku/pyvcroid2
```

Python3の対話型インタプリタを起動し以下を1行ずつ実行して、それぞれの`vc.listSpeakers()`の出力を記録する。
```
import pyvcroid2
vc = pyvcroid2.VcRoid2()

vc.loadLanguage("standard")
vc.loadVoice("aoi_emo_44")
vc.listSpeakers()

vc.loadVoice("akane_west_emo_44")
vc.listSpeakers()

vc.loadLanguage("standard_kansai")
vc.loadVoice("aoi_emo_44")
vc.listSpeakers()

vc.loadVoice("akane_west_emo_44")
vc.listSpeakers()
```

なおvoiceroid_daemonは今からプログラムを変更するのが大変なので
対応できるのはpyvcroid2だけになります。

**Comment by abokado0107** [comment]
お返事ありがとうございます。
私の環境ではVOICEROIDをインストールしている場所はprogram files (x84)下のAHSディレクトリなのですが
pyvcroid2で実行したところ
```
vc = pyvcroid2.VcRoid2()
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyvcroid2\pyvcroid2.py", line 72, in __init__
    self.__dll = windll.LoadLibrary(self.__install_path + "\\aitalked.dll")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Program Files\AHS\VOICEROID2\aitalked.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
と出てしまい、pyvcroid2.pyの該当箇所を直接
```
self.__install_path = "C:\\Program Files (x86)\\AHS\\VOICEROID2"
self.__install_path_x86 = "C:\\Program Files (x86)\\AHS\\VOICEROID2"
```
としたところ
```
vc = pyvcroid2.VcRoid2()
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyvcroid2\pyvcroid2.py", line 72, in __init__
    self.__dll = windll.LoadLibrary(self.__install_path + "\\aitalked.dll")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 は有効な Win32 アプリケーションではありません。
```
と出てしまいました。

**Comment by Nkyoku** [comment]
PythonとVOICEROIDの32bit/64bitを合わせないといけないので
Python 32bit版をインストールするか、64bit版のVOICEROID2のインストールをお願いします。

**Comment by abokado0107** [comment]
```
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvcroid2
>>> vc = pyvcroid2.VcRoid2()
>>> vc.loadLanguage("standard")
>>> vc.loadVoice("aoi_emo_44")
>>> vc.listSpeakers()
['aoi_emo_44']
>>> vc.loadVoice("akane_west_emo_44")
>>> vc.listSpeakers()
['akane_west_emo_44', 'aoi_emo_44']
>>> vc.loadLanguage("standard_kansai")
>>> vc.loadVoice("aoi_emo_44")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310-32\lib\site-packages\pyvcroid2\pyvcroid2.py", line 280, in loadVoice
    raise Exception(result)
Exception: ResultCode.ALREADY_LOADED
>>>
```
となりました。

**Comment by Nkyoku** [comment]
お返事が遅くなってすみません。
以下の2つのコードをPythonの対話型インタプリタで打ち込むと標準語と関西弁の音声が再生されませんか？
少なくともあかりちゃんはstandard_kansaiをロードしただけで関西弁で喋ってくれました。
```
import pyvcroid2, winsound
vc = pyvcroid2.VcRoid2()
vc.loadLanguage("standard")
vc.loadVoice("aoi_emo_44")
winsound.PlaySound(vc.textToSpeech("こんにちは。明日の天気は晴れの予報です")[0], winsound.SND_MEMORY)
```
`exit()`でpythonを終了して再びpythonを起動。
```
import pyvcroid2, winsound
vc = pyvcroid2.VcRoid2()
vc.loadLanguage("standard_kansai")
vc.loadVoice("akane_west_emo_44")
winsound.PlaySound(vc.textToSpeech("こんにちは。明日の天気は晴れの予報です")[0], winsound.SND_MEMORY)
```
